name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: lunrenyi/test_docker@main
    - name: Build the Docker image
      run: |
        echo "hello word!"
        pwd
        ls -l
        
