name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      run: |
        echo "hello word!"
        cat hello.py
        cd ..
        cat hello.py
        cd ..
        ls -l
        
